export type ToolApp = {
  name: string
  description: string
  href: string
  accent: string
  category: string
  focus: string
  displayName: string
  impact: string
  status?: string
}

// Central catalog for all /tools entries so both the UI and chatbot can stay in sync.
export const toolCatalog: ToolApp[] = [
  {
    name: "Targeted Redesign",
    description: "定向局部改造，生成可落地的款式升级方案。",
    href: "/redesign",
    accent: "from-emerald-400 to-green-500",
    category: "设计提案",
    focus: "款式升级",
    displayName: "改图",
    impact: "版型与面料双向联动",
  },
  {
    name: "Pattern Extraction",
    description: "一键提取图案纹理。",
    href: "/extract",
    accent: "from-sky-400 to-blue-500",
    category: "结构提取",
    focus: "纹理拆解",
    displayName: "印花提取",
    impact: "输出即刻复原",
  },
  {
    name: "Pattern Application",
    description: "借助 F3 将花型精准映射到不同版型与结构上。",
    href: "/apply",
    accent: "from-purple-300 to-indigo-500",
    category: "设计提案",
    focus: "版型映射",
    displayName: "印花应用",
    impact: "花型对位零偏差",
  },
  {
    name: "Text to Cloth",
    description: "从文字描述生成布料效果图与搭配建议。",
    href: "/text_to_cloth",
    accent: "from-rose-400 to-red-500",
    category: "设计提案",
    focus: "语义转图",
    displayName: "文生图",
    impact: "搭配建议随生成",
    status: "Beta",
  },
  {
    name: "Variants",
    description: "基于原款试配多种面料与配色，快速对比。",
    href: "/variants",
    accent: "from-fuchsia-400 to-pink-500",
    category: "设计提案",
    focus: "方案对比",
    displayName: "印花衍生",
    impact: "多版本一屏决策",
  },
  {
    name: "Stripe Extract",
    description: "针对条纹面料的提取与延展，保持纹路一致。",
    href: "/extract_stripe",
    accent: "from-orange-400 to-red-500",
    category: "结构提取",
    focus: "条纹延展",
    displayName: "条纹提取",
    impact: "织轴坐标自动校准",
    status: "Lab",
  },
  {
    name: "Plaid Extract",
    description: "精准拆解格纹结构，自动生成重复花型。",
    href: "/extract_plaid",
    accent: "from-blue-400 to-indigo-500",
    category: "结构提取",
    focus: "格纹拆解",
    displayName: "格纹拆解",
    impact: "循环节点智能标记",
  },
  {
    name: "High Resolution",
    description: "提升图像清晰度，适合提升素材和细节展示。",
    href: "/hi_res",
    accent: "from-slate-200 to-slate-500",
    category: "展示输出",
    focus: "细节修复",
    displayName: "高清增强",
    impact: "高清回传可直接上架",
  },
  {
    name: "Background Removal",
    description: "自动抠出主体并生成透明底图，适用于海报、电商主图与素材拼版。",
    href: "/remove_background",
    accent: "from-amber-200 to-orange-500",
    category: "展示输出",
    focus: "去除背景",
    displayName: "去除背景",
    impact: "透明底图即刻使用",
  },
  {
    name: "SVG Vectorization",
    description: "把参考图快速转成可编辑的 SVG 矢量文件。",
    href: "/svg",
    accent: "from-emerald-300 to-cyan-500",
    category: "展示输出",
    focus: "矢量复刻",
    displayName: "转矢量图",
    impact: "与 CAD 打通",
  },
  {
    name: "Virtual Try-On",
    description: "上传模特照，自动套用不同成衣效果。",
    href: "/try-on",
    accent: "from-amber-400 to-orange-500",
    category: "设计提案",
    focus: "成衣试穿",
    displayName: "虚拟试穿",
    impact: "模特&实样混排",
  },
  {
    name: "Seamless Patterns",
    description: "生成无缝铺陈的花型，支持重复与导出。",
    href: "/seamless-patterns",
    accent: "from-violet-400 to-purple-500",
    category: "设计提案",
    focus: "花型生成",
    displayName: "无缝花型",
    impact: "重复单元自动对齐",
  },
  {
    name: "Sheet F8",
    description: "设计档案、成本、技术规格一体化输出。",
    href: "/sheet",
    accent: "from-cyan-400 to-teal-500",
    category: "生产协同",
    focus: "资料打包",
    displayName: "档案打包",
    impact: "同步供应商视图",
  },
  {
    name: "CAD Toolkit",
    description: "调用 CAD 预设并输出 DXF 版型。",
    href: "/cad",
    accent: "from-lime-400 to-emerald-500",
    category: "生产协同",
    focus: "版型输出",
    displayName: "CAD 工具箱",
    impact: "DXF 兼容多系统",
  },
  {
    name: "Video Generation",
    description: "创建动态展示视频，适合成衣走秀呈现。",
    href: "/video-generation",
    accent: "from-indigo-400 to-blue-600",
    category: "展示输出",
    focus: "走秀短片",
    displayName: "走秀生成",
    impact: "一键成片含音乐",
  },
]
